#!/usr/bin/env python3
"""Per-config data coverage report — what each deployment HAS vs INHERITS vs is MISSING.

Reads the ``data`` manifests in ``configs/deployments/*.json`` (via :mod:`configs.loader`) and prints a
``config × data-input → status`` matrix, a per-config summary, and a drift check (every ``measured`` /
``derived`` artifact with a ``path`` must exist on disk). This is the canonical "which file provides what
data, and what's missing per config" view — replacing the ad-hoc ``profiling/docs/*.yaml``.

    python3 -m configs.coverage_report            # print the matrix + summary + drift check
    python3 -m configs.coverage_report --yaml     # (re)generate configs/coverage.yaml from the manifests
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

from configs.loader import REPO_ROOT, all_deployments

BENCH_BASE = Path("/mnt/100g/agent-bench/results/synthetic_distributional")
_ABBR = {"measured": "measured", "derived": "derived", "inherited": "inherit",
         "placeholder": "placehold", "missing": "MISSING"}


def _resolve(path: str) -> Path | None:
    """An existing path for a manifest entry — repo-relative, else the central bench store."""
    for cand in (REPO_ROOT / path, BENCH_BASE / path):
        if cand.exists():
            return cand
    return None


COVERAGE_YAML = REPO_ROOT / "configs" / "coverage.yaml"


def _yq(v) -> str:
    """Minimal YAML scalar quoting — quote strings with YAML-special chars."""
    s = str(v)
    return f'"{s}"' if any(c in s for c in ':#[]{}&*!|>%@`,') or s == "" else s


def emit_yaml(out: Path = COVERAGE_YAML) -> None:
    """Write configs/coverage.yaml — the per-config data tracker, generated from the manifests
    (calibrated configs first). Source of truth stays the deployment JSONs; regenerate to refresh."""
    deps = all_deployments()
    # Calibrated (own a measured decode grid) first, then the rest in loader order.
    deps = sorted(deps, key=lambda d: 0 if (d.data.get("decode_grid") or {}).get("status") == "measured" else 1)
    L = [
        "# configs/coverage.yaml — per-config data coverage tracker.",
        "# GENERATED by `python3 -m configs.coverage_report --yaml` from configs/deployments/*.json.",
        "# DO NOT hand-edit — edit the deployment manifests (the source of truth AND the wiring), then regenerate.",
        "# A config is calibrated when decode_grid is `measured`; the first-cut configs use the analytic decode",
        "# roofline (decode_grid: missing) and inherit the H100 ceiling/prefill grids. `not_measured` = the gaps.",
        "",
        "legend:",
        "  measured: own GPU runs / /mnt/100g data (path present)",
        "  derived: computed from this config's own measured inputs",
        "  inherited: borrowed from another config (see from)",
        "  placeholder: default stand-in, not validated for this config",
        "  missing: required by the predictor but no source -> a run is needed",
        "",
        "configs:",
    ]
    for d in deps:
        counts = Counter(e.get("status", "?") for e in d.data.values())
        L.append(f"  - gpu_key: {_yq(d.gpu_key)}")
        L.append(f"    model: {d.model}")
        L.append(f"    tp: {d.tp}")
        L.append(f"    engine: {d.engine}")
        L.append(f"    calibrated: {str((d.data.get('decode_grid') or {}).get('status') == 'measured').lower()}")
        L.append(f"    status_counts: {{{', '.join(f'{s}: {n}' for s, n in sorted(counts.items()))}}}")
        L.append("    inputs:")
        for inp, e in d.data.items():
            L.append(f"      {inp}: {e.get('status', '-')}")
        nm = [(inp, e) for inp, e in d.data.items() if e.get("status") not in ("measured", "derived")]
        if not nm:
            L.append("    not_measured: []   # fully calibrated")
        else:
            L.append("    not_measured:")
            for inp, e in nm:
                parts = [f"input: {inp}", f"status: {e.get('status')}"]
                if e.get("from"):
                    parts.append(f"from: {e['from']}")
                if e.get("note"):
                    parts.append(f"note: {_yq(e['note'])}")
                L.append(f"      - {{{', '.join(parts)}}}")
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out}  ({len(deps)} configs)")


def main() -> None:
    if "--yaml" in sys.argv:
        emit_yaml()
        return
    deps = all_deployments()
    inputs: list[str] = []
    for d in deps:
        for k in d.data:
            if k not in inputs:
                inputs.append(k)
    # One row per deployment, inputs as columns (many deployments share a gpu_key now, so a
    # deployment-per-column matrix would have duplicate headers; transpose for readability).
    lw = max((len(f"{d.gpu_key} [{d.model}]") for d in deps), default=20) + 2
    cw = 10

    print("\nDATA COVERAGE (configs/deployments)")
    print("config".ljust(lw) + "".join(i[:cw - 1].ljust(cw) for i in inputs))
    for d in deps:
        row = f"{d.gpu_key} [{d.model}]".ljust(lw)
        for inp in inputs:
            st = (d.data.get(inp) or {}).get("status", "-")
            row += _ABBR.get(st, st)[:cw - 1].ljust(cw)
        print(row)

    print("\nper-config status counts:")
    kw = max((len(f"{d.gpu_key} [{d.model}]") for d in deps), default=20) + 2
    for d in deps:
        counts = Counter(e.get("status", "?") for e in d.data.values())
        miss = [k for k, e in d.data.items() if e.get("status") == "missing"]
        line = "  " + f"{d.gpu_key} [{d.model}]".ljust(kw) + ", ".join(f"{n} {s}" for s, n in sorted(counts.items()))
        if miss:
            line += f"   MISSING: {miss}"
        print(line)

    print("\ndrift check (measured/derived artifacts must exist on disk):")
    bad = 0
    for d in deps:
        for k, e in d.data.items():
            if e.get("status") in ("measured", "derived") and e.get("path"):
                if _resolve(e["path"]) is None:
                    print(f"  !! {d.gpu_key} {k}: missing file {e['path']}")
                    bad += 1
    print("  all present ✓" if bad == 0 else f"  {bad} missing file(s) — see above")


if __name__ == "__main__":
    main()
